config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :wishlists do
    resources :items
  end
  
  get 'signup'  => 'users#new' 
  resources :users
  
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :wishlist
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_secure_password
    
    has_many :items, dependent: :destroy

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
    has_many :items, dependent: :destroy
    
    belongs_to :user
    
    validates :title,   presence: true,
                        length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      false
    end
  end
  
  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def show
    end
    
    def new
    end
    
    def create
        @wishlist = Wishlist.find(params[:wishlist_id])
        @item = @wishlist.items.create(item_params)
        redirect_to wishlist_path(@wishlist)
    end
    
    private
        def item_params
            params.require(:item).permit(:name, :url, :price, :active, :image_url)
        end
    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
    
    def create
        @user = User.find_by_email(params[:session][:email])
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            redirect_to '/'
        else
            redirect_to '/login'
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to '/'
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/'     
        else
            redirect_to '/signup'
        end
    end
    
    private
        def user_params
            params.require(:user).permit(:first_name, :last_name, :email, :password)
        end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wishlist_controller.rb
class WishlistController < ApplicationController
    def new
        @wishlist = Wishlist.new
    end

    def index
        @wishlists = Wishlist.all
    end

    def show
        @wishlist = Wishlist.find(params[:id])
    end
    
    def edit
        @wishlist = Wishlist.find(params[:id])
    end
    
    def create
        @wishlist = Wishlist.find(wishlist_params)
        
        if @wishlist.save(wishlist_params)
            redirect_to @wishlist
        else
            render 'new'
        end
    end
    
    def update
        @wishlist = Wishlist.find(params[:id])
        
        if @wishlist.update(wishlist_params)
            redirect_to @wishlist
        else
            render 'edit'
        end
    end
    
    private
        def wishlist_params
            params.require(:wishlist).permit(:title , :description)
        end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
    
    before_action :require_user
    
    def index
        @wishlists = Wishlist.where(user_id: current_user[:id])
    end
 
    def show
        @wishlist = Wishlist.includes(:user).find(params[:id])
    end
 
    def new
        @wishlist = Wishlist.new
    end
 
    def edit
        @wishlist = Wishlist.find(params[:id])
    end
 
    def create
        @wishlist = Wishlist.new(wishlist_params)
        @wishlist[:user_id] = current_user[:id]
        if @wishlist.save
            redirect_to @wishlist
        else
            render 'new'
        end
    end
 
    def update
        @wishlist = Wishlist.find(params[:id])
        if @wishlist.update(wishlist_params)
            redirect_to @wishlist
        else
            render 'edit'
        end
    end
    
    def destroy
        @wishlist = Wishlist.find(params[:id])
        @wishlist.destroy
        
        redirect_to wishlist_path
    end

    private
        def wishlist_params
            params.require(:wishlist).permit(:title, :description)
        end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/items/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="form-horizontal">
      <fieldset>
        <legend>Add Item</legend>
        <%= form_for([@wishlist, @wishlist.items.build]) do |f| %>
          <div class="col-md-12 form-group label-placeholder">
            <%= f.label :name , class: "control-label" %>
            <%= f.text_field :name , class: "form-control" %>
          </div>
          <div class="col-md-12 form-group label-placeholder">
            <%= f.label :url , class: "control-label" %>
            <%= f.text_field :url , class: "form-control" %>
          </div>
          <div class="col-md-5 form-group label-placeholder">
            <%= f.label :price , class: "control-label" %>
            <%= f.text_field :price , class: "form-control" %>
          </div>
          <div class="col-md-7 form-group label-placeholder">
            <%= f.label :image_url , class: "control-label" %>
            <%= f.text_field :image_url , class: "form-control" %>
          </div>
          
          <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
              <button type="button" class="btn btn-default">Cancel</button>
              <%= f.submit(class: "btn btn-raised btn-primary") %>
            </div>
          </div>
        <% end %>
      </fieldset>
    </div>
  </div>
</div>

app/views/items/_item.html.erb
<div class="list-group-item">
    <div class="row-picture">
        <img class="circle" src="<%= item.image_url %>" alt="icon">
    </div>
    <div class="row-content">
        <a href="<%= item.url %>">
            <h2 class="list-group-item-heading"><%= item.name %></h2>
        </a>
        <p class="list-group-item-text">
            <span class="badge">€ <%= item.price %></span>
        </p>
    </div>
</div>
<div class="list-group-separator"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Desiderio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>
    <div style="height: 1px;" aria-expanded="false" class="navbar-collapse navbar-responsive-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/wishlists">My Wishlists<div class="ripple-container"></div></a></li>
        <li><a href="/wishlists/new">New</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group is-empty">
          <input class="form-control col-md-8" placeholder="Search" type="text">
        <span class="material-input"></span></div>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><a href="#"><%= current_user.first_name %></a></li>
          <li><%= link_to "Logout", logout_path, method: 'delete' %></li>

        <% else %>
          <li><%= link_to "Login", 'login' %></li>
          <li><%= link_to "Signup", 'signup' %></li>
        <% end %>
      </ul>
      
    </div>

                
  </div>
</div>
<div style="display: none;" id="source-button" class="btn btn-primary btn-xs">&lt; &gt;</div></div>
  
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="form-horizontal">
      <fieldset>
        <legend>Sign up</legend>
        <%= form_for(@user) do |f| %>
          
          <div class="form-group label-placeholder">
            <%= f.label :first_name , class: "control-label" %>
            <%= f.text_field :first_name , class: "form-control" %>
          </div>
          <div class="form-group label-placeholder">
            <%= f.label :last_name , class: "control-label" %>
            <%= f.text_field :last_name , class: "form-control" %>
          </div>
          <div class="form-group label-placeholder">
            <%= f.label :email , class: "control-label" %>
            <%= f.text_field :email , class: "form-control" %>
          </div>
          <div class="form-group label-placeholder">
            <%= f.label :password , class: "control-label" %>
            <%= f.password_field :password , class: "form-control" %>
          </div>
          
          <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
              <button type="button" class="btn btn-default">Cancel</button>
              <%= f.submit "Create account" , class: "btn btn-raised btn-primary" %>
            </div>
          </div>
        <% end %>
      </fieldset>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Wishlists</h1>

<p>
C'e' una stella su nel ciel<br/>
che ogni sogno puo avverar<br/>
e la gioia piu serena sa portar<br/>
e se lei tu schiudi il cuor<br/>
con fiducia con amor<br/>
quella stella su nel ciel<br/>
ti ascoltera'</p>


<%= link_to 'My Wishlists' , controller: 'wishlists' %>
<%= link_to 'Start wishing', new_wishlist_path %>

app/views/wishlist/new.html.erb
<h1>New Wishlist</h1>

<%= form_for :wishlist, url: wishlist_index_path do |f| %>
    <!-- Validation errors -->
    <% if @wishlist.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@wishlist.errors.count, "error") %>
                prohibited this wishlist from being saved:
            </h2>
            <ul>
                <% @wishlist.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>


    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>
    <%= f.submit %>
<% end %>

app/views/wishlists/_form.html.erb
<%= form_for @wishlist do |f| %>
    <!-- Validation errors -->
    <% if @wishlist.errors.any? %>
        <div id="error_explanation" class="text-danger">
            <p><%= pluralize(@wishlist.errors.count, "error") %>
                prohibited this wishlist from being saved:
            </hp>
            <ul>
                <% @wishlist.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="form-group label-placeholder">
        <%= f.label :title , class: "control-label" %>
        <%= f.text_field :title , class: "form-control" %>
    </div>
    <%= f.submit(class: "btn btn-raised btn-primary")  %>
    
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form' %>

<%= link_to 'Back', wishlist_path %>

app/views/wishlists/index.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>Wishlists</h1>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <div class="list-group">
        <% @wishlists.each do |wishlist| %>
        <div class="row-content">
        
            <a href="<%= wishlist_path(wishlist) %>">
                <h4 class="list-group-item-heading"><%= wishlist.title %></h4>
            </a>
            <p class="list-group-item-text">
                <span class="badge"><%= wishlist.description %></span>
            </p>
        </div>
        <% end %>
        </div>
    </div>
</div>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>
<%= render 'form' %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<div class="row">
<div class="col-xs-12">

  <h1><%= @wishlist.title %></h1>
  <%= link_to 'Back', wishlists_path , class: "btn btn-xs btn-default" %>
  <%= link_to 'Edit', edit_wishlist_path(@wishlist) , class: "btn btn-xs btn-default" %> 

  <p class="small">
    <%= @wishlist.description %>
    <%= @wishlist.user.email %>
  </p>

  <hr />
  <div class="list-group">
    <%= render @wishlist.items %>
  </div>

  <div class="well">
    <%= render 'items/form' %>
  </div>
  </div>
</div>